from datetime import datetime
from decimal import Decimal
from sqlalchemy import String,Integer,Boolean,DateTime,ForeignKey,Numeric,Text,func
from sqlalchemy.orm import Mapped,mapped_column,relationship
from app.db import Base
class User(Base):
    __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); full_name:Mapped[str]=mapped_column(String(160)); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[str]=mapped_column(String(30),default='customer',index=True); is_active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); orders:Mapped[list['Order']]=relationship(back_populates='user')
class Product(Base):
    __tablename__='products'; id:Mapped[int]=mapped_column(primary_key=True); slug:Mapped[str]=mapped_column(String(180),unique=True,index=True); title:Mapped[str]=mapped_column(String(220),index=True); author:Mapped[str]=mapped_column(String(160)); category:Mapped[str]=mapped_column(String(120),index=True); product_type:Mapped[str]=mapped_column(String(30)); price:Mapped[Decimal]=mapped_column(Numeric(10,2)); old_price:Mapped[Decimal|None]=mapped_column(Numeric(10,2),nullable=True); stock:Mapped[int]=mapped_column(Integer,default=0); description:Mapped[str]=mapped_column(Text,default=''); cover_color:Mapped[str]=mapped_column(String(40),default='book-a'); cover_image_url:Mapped[str|None]=mapped_column(String(500),nullable=True); digital_file_url:Mapped[str|None]=mapped_column(String(500),nullable=True); is_active:Mapped[bool]=mapped_column(Boolean,default=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Order(Base):
    __tablename__='orders'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); status:Mapped[str]=mapped_column(String(40),default='pending_payment',index=True); payment_method:Mapped[str]=mapped_column(String(20)); payment_status:Mapped[str]=mapped_column(String(30),default='pending',index=True); delivery_method:Mapped[str]=mapped_column(String(30)); subtotal:Mapped[Decimal]=mapped_column(Numeric(10,2)); shipping_fee:Mapped[Decimal]=mapped_column(Numeric(10,2),default=0); total:Mapped[Decimal]=mapped_column(Numeric(10,2)); shipping_name:Mapped[str]=mapped_column(String(160)); shipping_email:Mapped[str]=mapped_column(String(255)); shipping_phone:Mapped[str]=mapped_column(String(40),default=''); shipping_address:Mapped[str]=mapped_column(String(255),default=''); shipping_city:Mapped[str]=mapped_column(String(120),default=''); shipping_state:Mapped[str]=mapped_column(String(60),default=''); shipping_zip:Mapped[str]=mapped_column(String(20),default=''); stripe_checkout_session_id:Mapped[str|None]=mapped_column(String(255),nullable=True,unique=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); user:Mapped[User]=relationship(back_populates='orders'); items:Mapped[list['OrderItem']]=relationship(back_populates='order',cascade='all, delete-orphan',lazy='selectin')
class OrderItem(Base):
    __tablename__='order_items'; id:Mapped[int]=mapped_column(primary_key=True); order_id:Mapped[int]=mapped_column(ForeignKey('orders.id',ondelete='CASCADE'),index=True); product_id:Mapped[int]=mapped_column(ForeignKey('products.id'),index=True); title:Mapped[str]=mapped_column(String(220)); product_type:Mapped[str]=mapped_column(String(30)); quantity:Mapped[int]=mapped_column(Integer); unit_price:Mapped[Decimal]=mapped_column(Numeric(10,2)); digital_file_url:Mapped[str|None]=mapped_column(String(500),nullable=True); order:Mapped[Order]=relationship(back_populates='items')
